#!/usr/bin/env python3
"""
Combines rsfMRI_processing_summary_with_anat_appendix.pptx (39 slides -- the
session review + appendix) and Data_Analysis_Scripts_Overview.pptx (25
slides -- how the scripts work) into one sequential deck: a new title +
master contents, then each source deck's own content (minus its own
title/contents slides, which the new combined title/contents replace),
separated by a "PART" divider.

python-pptx has no built-in cross-presentation "copy slide" API, so this
copies each source slide's shape XML (copy_slide()) into a freshly-added
blank slide in the new presentation, including background fill and any
embedded images (re-relating each picture's blob into the destination
package and rewriting its r:embed rId -- otherwise copied <a:blip> elements
would point at relationship IDs that don't exist in the new file).

A final pass (renumber_and_fix_references) then renumbers every page-number
badge to its true combined-deck position and remaps the slide-number
references named in the rsfMRI appendix's own index slides, so the result
reads as one continuous document rather than decks stitched together.

Also appends a "PART III -- Data Statistics" section at the end: 4 pre-made
figures (scan_sessions_5groups.png, age_range_boxplot_5groups.png,
interval_summary_table.png, interval_summary_rangeplot.png) covering the
broader HCP-Aging AABC cohort's scan-session counts, age distributions, and
inter-visit intervals -- not generated by any script in this folder, just
placed in the project root and embedded here in the order given.

Standard command:
  python3 build_combined_presentation.py

Output:
  Combined_rsfMRI_and_Scripts_Overview.pptx (project root, one directory up
  from this scripts folder)
"""
import io
import re
import copy
from pathlib import Path

from pptx import Presentation
from pptx.util import Emu, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
PRESENTATIONS_DIR = ROOT / "presentations"
SRC_RSFMRI = PRESENTATIONS_DIR / "rsfMRI_processing_summary_with_anat_appendix.pptx"
SRC_SCRIPTS = PRESENTATIONS_DIR / "Data_Analysis_Scripts_Overview.pptx"
DST = PRESENTATIONS_DIR / "Combined_rsfMRI_and_Scripts_Overview.pptx"

NAVY = RGBColor(0x0B, 0x25, 0x45)
TEAL = RGBColor(0x2E, 0xC4, 0xB6)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
SLATE_LIGHT = RGBColor(0xD9, 0xE1, 0xE8)
SLATE_MUTED = RGBColor(0x55, 0x66, 0x77)
DIM_SLATE = RGBColor(0x8A, 0x9B, 0xB0)

SLIDE_W = Emu(12191695)
SLIDE_H = Emu(6858000)
MARGIN = Emu(502920)


def set_solid_bg(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def add_textbox(slide, left, top, width, height, text, size, color, bold=False,
                 font="Calibri", align=PP_ALIGN.LEFT):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    lines = text.split("\n")
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        run = p.add_run()
        run.text = line
        run.font.name = font
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color
    return box


def copy_slide(dest_prs, src_slide, dest_layout):
    """Deep-copy src_slide's background + every shape into a new slide of
    dest_prs, re-relating any embedded images into the destination package."""
    dest_slide = dest_prs.slides.add_slide(dest_layout)

    for shp in list(dest_slide.shapes):
        shp._element.getparent().remove(shp._element)

    src_cSld = src_slide._element.find(qn("p:cSld"))
    dest_cSld = dest_slide._element.find(qn("p:cSld"))
    src_bg = src_cSld.find(qn("p:bg"))
    dest_bg = dest_cSld.find(qn("p:bg"))
    if dest_bg is not None:
        dest_cSld.remove(dest_bg)
    if src_bg is not None:
        dest_cSld.insert(0, copy.deepcopy(src_bg))

    src_spTree = src_slide.shapes._spTree
    dest_spTree = dest_slide.shapes._spTree
    skip_tags = {qn("p:nvGrpSpPr"), qn("p:grpSpPr")}
    for elem in list(src_spTree):
        if elem.tag in skip_tags:
            continue
        new_elem = copy.deepcopy(elem)
        for blip in new_elem.iter(qn("a:blip")):
            r_embed = blip.get(qn("r:embed"))
            if r_embed:
                image_part = src_slide.part.related_part(r_embed)
                _new_part, new_rid = dest_slide.part.get_or_add_image_part(
                    io.BytesIO(image_part.blob)
                )
                blip.set(qn("r:embed"), new_rid)
        dest_spTree.append(new_elem)

    return dest_slide


def new_title_slide(prs, blank_layout):
    slide = prs.slides.add_slide(blank_layout)
    set_solid_bg(slide, NAVY)
    accent = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, Emu(6700000), SLIDE_W, Emu(38100))
    accent.fill.solid(); accent.fill.fore_color.rgb = TEAL
    accent.line.fill.background()
    add_textbox(slide, MARGIN, Emu(2200000), Emu(11186760), Emu(320000),
                "HCP-AGING · AABC RELEASE 2", 14, TEAL, bold=True)
    add_textbox(slide, MARGIN, Emu(2560000), Emu(11186760), Emu(1300000),
                "rfMRI Processing Summary\n& Data Analysis Scripts", 38, WHITE, bold=True)
    add_textbox(slide, MARGIN, Emu(4050000), Emu(11186760), Emu(500000),
                "Part I — session review, QC, and reference appendix.\n"
                "Part II — how the underlying analysis scripts work, end to end.",
                16, SLATE_LIGHT)
    add_textbox(slide, MARGIN, Emu(6200000), Emu(11186760), Emu(300000),
                "Combined deck — rsfMRI_processing_summary_with_anat_appendix.pptx "
                "+ Data_Analysis_Scripts_Overview.pptx", 10.5, DIM_SLATE)
    return slide


def new_contents_slide(prs, blank_layout):
    slide = prs.slides.add_slide(blank_layout)
    set_solid_bg(slide, RGBColor(0xF4, 0xF7, 0xFA))
    band = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, Emu(1051560))
    band.fill.solid(); band.fill.fore_color.rgb = NAVY
    band.line.fill.background()
    accent = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, Emu(1051560), SLIDE_W, Emu(38100))
    accent.fill.solid(); accent.fill.fore_color.rgb = TEAL
    accent.line.fill.background()
    add_textbox(slide, MARGIN, Emu(146304), Emu(9144000), Emu(274320), "CONTENTS", 12, TEAL, bold=True)
    add_textbox(slide, MARGIN, Emu(402336), Emu(10515600), Emu(594360), "Master Agenda", 26, WHITE, bold=True)
    add_textbox(slide, Emu(11094415), Emu(6492240), Emu(640080), Emu(274320), "2", 9, RGBColor(0x55, 0x66, 0x77))

    items = [
        ("PART I", "rfMRI Processing Summary", "Session review (8 sections) + reference appendix "
         "(pipeline suite, sources, atlas survey, understanding anatomical data)"),
        ("PART II", "Data Analysis Scripts — Technical Reference", "Data hierarchy, organize_hcp_data.py, "
         "cross-sectional analysis (v1/v2), FC pipeline (v1/v2/v3 + batch), prerequisites, run sequence"),
    ]
    y = Emu(1750000)
    for num, title, desc in items:
        add_textbox(slide, MARGIN, y, Emu(1400000), Emu(320000), num, 18, TEAL, bold=True)
        add_textbox(slide, MARGIN + Emu(1450000), y, Emu(9200000), Emu(320000), title, 18, NAVY, bold=True)
        add_textbox(slide, MARGIN + Emu(1450000), y + Emu(380000), Emu(9200000), Emu(500000), desc, 12, RGBColor(0x55, 0x66, 0x77))
        y += Emu(1400000)
    return slide


def new_part_divider(prs, blank_layout, part_label, title, description, page_num):
    slide = prs.slides.add_slide(blank_layout)
    set_solid_bg(slide, NAVY)
    bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, Emu(3100000), Emu(200000), Emu(900000))
    bar.fill.solid(); bar.fill.fore_color.rgb = TEAL
    bar.line.fill.background()
    add_textbox(slide, Emu(900000), Emu(2950000), Emu(4000000), Emu(320000), part_label, 16, TEAL, bold=True)
    add_textbox(slide, Emu(900000), Emu(3280000), Emu(10300000), Emu(900000), title, 36, WHITE, bold=True)
    add_textbox(slide, Emu(900000), Emu(4300000), Emu(9600000), Emu(600000), description, 14.5, SLATE_LIGHT)
    add_textbox(slide, Emu(11094415), Emu(6492240), Emu(640080), Emu(274320), str(page_num), 9, DIM_SLATE)
    return slide


LIGHT_BG = RGBColor(0xF4, 0xF7, 0xFA)
CONTENT_W = Emu(11201400)
STATS_FOOTER = "HCP-Aging AABC Release 2  ·  Data Statistics"


def add_header(slide, eyebrow, title, page_num):
    band = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, Emu(1051560))
    band.fill.solid(); band.fill.fore_color.rgb = NAVY
    band.line.fill.background()
    accent = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, Emu(1051560), SLIDE_W, Emu(38100))
    accent.fill.solid(); accent.fill.fore_color.rgb = TEAL
    accent.line.fill.background()
    add_textbox(slide, MARGIN, Emu(146304), Emu(9144000), Emu(274320), eyebrow, 12, TEAL, bold=True)
    add_textbox(slide, MARGIN, Emu(402336), Emu(10515600), Emu(594360), title, 26, WHITE, bold=True)
    add_textbox(slide, Emu(11277295), Emu(146304), Emu(548640), Emu(274320), str(page_num), 12, SLATE_LIGHT)


def add_footer(slide, page_num):
    add_textbox(slide, MARGIN, Emu(6492240), Emu(7315200), Emu(274320), STATS_FOOTER, 9, SLATE_MUTED)
    add_textbox(slide, Emu(11094415), Emu(6492240), Emu(640080), Emu(274320), str(page_num), 9, SLATE_MUTED)


def new_content_slide(prs, blank_layout, eyebrow, title, page_num):
    slide = prs.slides.add_slide(blank_layout)
    set_solid_bg(slide, LIGHT_BG)
    add_header(slide, eyebrow, title, page_num)
    add_footer(slide, page_num)
    return slide


def add_picture_fit(slide, img_path, area_left, area_top, area_w, area_h):
    """Fit an image into (area_w, area_h), preserving aspect ratio, centered."""
    from PIL import Image
    with Image.open(img_path) as im:
        iw, ih = im.size
    img_ratio = iw / ih
    area_ratio = area_w / area_h
    if img_ratio > area_ratio:
        w = area_w
        h = int(w / img_ratio)
    else:
        h = area_h
        w = int(h * img_ratio)
    left = area_left + (area_w - w) // 2
    top = area_top + (area_h - h) // 2
    slide.shapes.add_picture(str(img_path), left, top, width=w, height=h)


def build():
    src_rsfmri = Presentation(str(SRC_RSFMRI))
    src_scripts = Presentation(str(SRC_SCRIPTS))

    dest = Presentation()
    dest.slide_width = SLIDE_W
    dest.slide_height = SLIDE_H
    blank_layout = dest.slide_layouts[6]

    new_title_slide(dest, blank_layout)
    new_contents_slide(dest, blank_layout)

    new_part_divider(
        dest, blank_layout, "PART I",
        "rfMRI Processing Summary",
        "Session review across 8 sections (dataset overview through summary), "
        "plus a reference appendix (pipeline suite, sources, atlas survey, "
        "understanding anatomical data).",
        page_num=3,
    )
    for slide in list(src_rsfmri.slides)[2:]:  # skip its own title + contents
        copy_slide(dest, slide, blank_layout)

    new_part_divider(
        dest, blank_layout, "PART II",
        "Data Analysis Scripts — Technical Reference",
        "How the scripts behind Part I actually work: data hierarchy, "
        "organize_hcp_data.py, cross-sectional analysis (v1/v2 + batch), the FC "
        "pipeline (v1/v2 + batch), prerequisites, and run order.",
        page_num=41,
    )
    for slide in list(src_scripts.slides)[2:]:  # skip its own title + contents
        copy_slide(dest, slide, blank_layout)

    new_part_divider(
        dest, blank_layout, "PART III",
        "Data Statistics",
        "Scan session counts, age distributions, and inter-visit interval ranges "
        "across the broader HCP-Aging AABC cohort, split by 5 demographic/cognitive filter groups.",
        page_num=64,
    )
    stats_figures = [
        ("scan_sessions_5groups.png", "Scan Sessions by Visit — 5 Groups",
         "Session counts at each visit (V1–V4), for all subjects and 4 progressively-filtered subgroups (age, MoCA cognitive score)."),
        ("age_range_boxplot_5groups.png", "Age Range by Visit — 5 Groups",
         "Min/25th/median/75th/max age at each visit, same 5 groups."),
        ("interval_summary_table.png", "Inter-Visit Interval Summary — Min / Max by Subject",
         "Shortest and longest gap between visits, consecutive (V1→V2, V2→V3, V3→V4) and cumulative from V1 (V1→V3, V1→V4)."),
        ("interval_summary_rangeplot.png", "Inter-Visit Interval Range — Visual Summary",
         "Same min/max interval data as the table above, plotted as a range for each visit pair."),
    ]
    for page_offset, (fname, title, desc) in enumerate(stats_figures, start=1):
        s = new_content_slide(dest, blank_layout, "DATA STATISTICS", title, 64 + page_offset)
        add_textbox(s, MARGIN, Emu(1230000), CONTENT_W, Emu(320000), desc, 11, SLATE_MUTED)
        add_picture_fit(s, ROOT / "results" / fname, MARGIN, Emu(1650000), CONTENT_W, Emu(4700000))

    renumber_and_fix_references(dest)

    dest.save(str(DST))
    print(f"Saved: {DST}")
    print(f"Total slides: {len(dest.slides)}")


# ---- Final pass: every copied slide keeps its ORIGINAL deck's own page-number
# badge and (for two rsfMRI appendix dividers) body text that references slide
# numbers by name -- both need remapping to the combined deck's actual 1-63
# positions so the merged deck reads as one continuous document, not two
# decks stitched together.
BADGE_POSITIONS = {(11277295, 146304), (11094415, 6492240), (502920, 6492240)}


def fix_page_badges(dest):
    for i, slide in enumerate(dest.slides, start=1):
        for sh in slide.shapes:
            if not sh.has_text_frame:
                continue
            txt = sh.text_frame.text.strip()
            if not txt.isdigit():
                continue
            if (sh.left, sh.top) not in BADGE_POSITIONS:
                continue
            # Scripts-deck section dividers put their (only) badge bottom-left;
            # move it to the same bottom-right spot every other slide uses.
            if (sh.left, sh.top) == (502920, 6492240):
                sh.left = Emu(11094415)
            run = sh.text_frame.paragraphs[0].runs[0]
            run.text = str(i).zfill(len(txt)) if txt.startswith("0") else str(i)


# rsfMRI-deck body text already correctly names ITS OWN (post-divider-insertion,
# 38-slide) slide numbers after fix_stale_slide_references.py -- within the
# combined deck those slides sit at local_number + 1 (title+contents+PartI
# divider precede them, minus the 2 slides of its own title+contents skipped).
RSFMRI_TEXT_REMAP = {
    # "(Slide 5)"/"see Slide 5" were already fixed to say "Slide 8" locally
    # by fix_stale_slide_references.py -> +1 for the combined deck = 9
    "Slide 8": "Slide 9",
    "slides 8 and 10": "slides 9 and 11",
    "Slide 22": "Slide 23", "Slide 23": "Slide 24",
    "Slides 25–33": "Slides 26–34", "Slides 35–38": "Slides 36–39",
    "Slide 25": "Slide 26", "Slide 26": "Slide 27", "Slide 27": "Slide 28",
    "Slides 28–30": "Slides 29–31", "Slides 31–32": "Slides 32–33", "Slide 33": "Slide 34",
    "Slide 35": "Slide 36", "Slide 36": "Slide 37", "Slide 37": "Slide 38", "Slide 38": "Slide 39",
    "Slide 39": "Slide 40",
}
# Single-pass regex: the original text is scanned once and every match is
# replaced via lookup -- critical, since sequential str.replace() calls over
# this dict would cascade (a "Slide 25"->"Slide 26" replacement would then
# get caught -- and wrongly re-replaced -- by the "Slide 26"->"Slide 27" rule).
_RSFMRI_PATTERN = re.compile(
    "|".join(re.escape(k) for k in sorted(RSFMRI_TEXT_REMAP, key=len, reverse=True))
)


def fix_index_text(dest):
    # Part I content occupies combined slides 4-40 (rsfMRI's own local 3-39 + 1)
    for slide in list(dest.slides)[3:40]:
        for sh in slide.shapes:
            if not sh.has_text_frame:
                continue
            for para in sh.text_frame.paragraphs:
                for run in para.runs:
                    if _RSFMRI_PATTERN.search(run.text):
                        run.text = _RSFMRI_PATTERN.sub(lambda m: RSFMRI_TEXT_REMAP[m.group(0)], run.text)


def renumber_and_fix_references(dest):
    fix_index_text(dest)
    fix_page_badges(dest)


if __name__ == "__main__":
    build()
